//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.3.
// qwq.rc

#define IDC_LST1                            1001
#define IDC_BTN1                            1002
#define IDC_BTN2                            1004
#define IDC_LSV_DRI                         1005
#define IDC_PGB1                            1107
#define IDC_PROG_TITLE1                     1108
#define IDC_EDT1                            1109
#define IDC_LSV_IMG                         1110

#define IDD_DLG1                            1000
#define IDD_DLG2                            1003
#define IDD_DLG3                            1106

#define TXT_1                               10001
#define TXT_2                               10002

#define MANIFEST                            24

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1111
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
